<a href="https://colab.research.google.com/github/subharanjana25/Machine_Learning/blob/ml_algorithms-from-scratch/NeuralNetwork_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [ ]:
y=np.array([[1],[0],[1]])

In [ ]:
y

array([[1],
       [0],
       [1]])

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [ ]:
def derivative_sigmoid(x):
  return x*(1-x)

In [ ]:
epoch=5000
lr=0.1
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1

In [ ]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
bh=np.random.uniform(size=(1,hidden_neurons))
wo=np.random.uniform(size=(hidden_neurons,output_neurons))
bo=np.random.uniform(size=(1,output_neurons))

In [ ]:
for i in range(epoch):
    # Forward pass
    hidden_input = np.dot(x, wh) + bh
    hidden_activation = sigmoid(hidden_input)
    output_layer = np.dot(hidden_activation, wo) + bo
    output = sigmoid(output_layer)

    # Backward pass
    E = y - output
    slope_output = derivative_sigmoid(output)
    slope_hidden = derivative_sigmoid(hidden_activation)
    d_output = E * slope_output
    error_hidden = d_output.dot(wo.T)
    d_hidden = error_hidden * slope_hidden

    # Update weights and biases
    wo += hidden_activation.T.dot(d_output) * lr
    bo += np.sum(d_output, axis=0, keepdims=True) * lr
    wh += x.T.dot(d_hidden) * lr
    bh += np.sum(d_hidden, axis=0, keepdims=True) * lr

In [ ]:
output

array([[0.97162289],
       [0.03905493],
       [0.9772142 ]])

In [ ]:
correct_predictions = 0

for i in range(len(x)):
    # Forward pass
    hidden_input = np.dot(x[i], wh) + bh
    hidden_activation = sigmoid(hidden_input)
    output_layer = np.dot(hidden_activation, wo) + bo
    output = sigmoid(output_layer)

    # Check if the prediction is correct
    predicted_label = 1 if output[0] > 0.5 else 0
    actual_label = y[i][0]
    if predicted_label == actual_label:
        correct_predictions += 1

# Calculate accuracy
accuracy = correct_predictions / len(x) * 100
print("Accuracy:", accuracy, "%")

Accuracy: 100.0 %
